"""empty message

Revision ID: 57b535cd2a59
Revises: 0a665602e744
Create Date: 2022-08-05 10:24:46.552889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b535cd2a59'
down_revision = '0a665602e744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('spotName', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'spotName')
    # ### end Alembic commands ###
