"""empty message

Revision ID: 0a665602e744
Revises: c1f17d06dfde
Create Date: 2022-08-03 22:52:18.038572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a665602e744'
down_revision = 'c1f17d06dfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('username', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'username')
    # ### end Alembic commands ###
