"""empty message

Revision ID: 086f19d0ab10
Revises: 0f1c1bbb7b03
Create Date: 2022-08-24 16:38:39.436318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086f19d0ab10'
down_revision = '0f1c1bbb7b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotId', sa.Integer(), nullable=False),
    sa.Column('wishlistId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spotId'], ['spots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlistId'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishspots')
    op.drop_table('wishlists')
    # ### end Alembic commands ###
