"""empty message

Revision ID: 36c0275fce0f
Revises: 87a8d14e830d
Create Date: 2022-08-02 19:17:59.819988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c0275fce0f'
down_revision = '87a8d14e830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###
