"""empty message

Revision ID: 0f1c1bbb7b03
Revises: 7dab32fa3cc2
Create Date: 2022-08-07 23:37:13.707468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1c1bbb7b03'
down_revision = '7dab32fa3cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spots', 'streetAdress',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spots', 'streetAdress',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###
