"""empty message

Revision ID: c1f17d06dfde
Revises: 36c0275fce0f
Create Date: 2022-08-03 15:23:19.183479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f17d06dfde'
down_revision = '36c0275fce0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('img1', sa.String(length=1000), nullable=True))
    op.add_column('spots', sa.Column('img2', sa.String(length=1000), nullable=True))
    op.add_column('spots', sa.Column('img3', sa.String(length=1000), nullable=True))
    op.add_column('spots', sa.Column('img4', sa.String(length=1000), nullable=True))
    op.add_column('spots', sa.Column('img5', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'img5')
    op.drop_column('spots', 'img4')
    op.drop_column('spots', 'img3')
    op.drop_column('spots', 'img2')
    op.drop_column('spots', 'img1')
    # ### end Alembic commands ###
