"""empty message

Revision ID: f73212bf6e06
Revises: 57b535cd2a59
Create Date: 2022-08-07 23:20:03.053334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73212bf6e06'
down_revision = '57b535cd2a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('img6', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'img6')
    # ### end Alembic commands ###
