"""empty message

Revision ID: 7dab32fa3cc2
Revises: f73212bf6e06
Create Date: 2022-08-07 23:36:56.023908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dab32fa3cc2'
down_revision = 'f73212bf6e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spots', 'streetAdress',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spots', 'streetAdress',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###
